INSERT INTO COURSE(CRS_ID,CRS_NAME,ACT_FEE) VALUES(1,'Networking Essentials',2800);
INSERT INTO COURSE(CRS_ID,CRS_NAME,ACT_FEE) VALUES(2,'Java',3500);
INSERT INTO COURSE(CRS_ID,CRS_NAME,ACT_FEE) VALUES(3,'Angular JS',3000);